fix: #1016
casdoor/casdoor pull request #1017
Opened 2022-08-14 11:48 UTC by kofj

Signed-off-by: 疯魔慕薇 <kfanjian@gmail.com>

2022-08-14 13:03 UTC, kofj commented
@hsluoyz review pls, thx.

2022-08-14 15:07 UTC, hsluoyz requested changes

2022-08-14 15:07 UTC, hsluoyz commented on object/check.go
>  	if application.IsSignupItemVisible("Username") {
Modify to pure text:

![B`S`8HO4PLE5)`V $)STUHN](https://user-images.githubusercontent.com/3787410/184543085-b8a4e960-cc24-4ab2-9686-f5c59b9ce16b.png)

2022-08-14 15:07 UTC, hsluoyz commented on object/check.go
> +		if username[0] >= '0' && username[0] <= '9' {
Use `IsDigit()`

2022-08-15 16:14 UTC, hsluoyz approved these changes

2022-08-15 16:14 UTC, merged