feat: add defaultApplication for Orgnization
casdoor/casdoor pull request #1111
Opened 2022-09-08 03:55 UTC by seriouszyx

Signed-off-by: Yixiang Zhao <seriouszyx@foxmail.com>

2022-09-09 09:12 UTC, hsluoyz requested changes

2022-09-09 09:12 UTC, hsluoyz commented on object/organization.go
> +		return getApplication("admin", "app-built-in")
Don't use "app-built-in"

2022-09-10 10:28 UTC, seriouszyx commented
demo link: 

1. http://101.43.193.167:8000/login
2. http://101.43.193.167:8000/login/testorg
3. http://101.43.193.167:8000/login/testorg2

2022-09-10 11:43 UTC, hsluoyz approved these changes

2022-09-10 12:41 UTC, merged