fix: forget password and sign up router
casdoor/casdoor pull request #1227
Opened 2022-10-17 21:52 UTC by imchell

Fix: #1181 

![page router](https://us1.myximage.com/2022/10/18/3d0ae5d0a5c4e23b994a1b809d880b42.gif)

2022-10-20 01:27 UTC, hsluoyz commented
@leo220yuyaodog plz review

2022-10-20 01:31 UTC, hsluoyz requested changes

2022-10-20 01:31 UTC, hsluoyz commented on web/src/Setting.js
> +      return "application.forgetUrl";
`application.forgetUrl` can be other domain's URL

2022-10-20 02:34 UTC, leo220yuyaodog commented
@imchell Actually, now from the login page fo to the signup and forget page is the SPA router. It can not invoke the page refresh.  From the signup page to login page will refresh the browser. 

When switch the pages will appears a short white pages, because react renders background image. The backgroud image url is from the react state `application`. And the `LoginPage`, `SignupPage` have their owe state  `application`, so react renders background iamge again, cause the problem. 

I have an idea that extract the background div to the father component. Then when switch the pages, the background will not render again.  Do you hava other good implenmentation metheds?

2022-10-21 23:00 UTC, imchell commented
@leo220yuyaodog Thanks for reviewing. Yes, the background page reloads while switching between `LoginPage` and `SignupPage`. I'm not a react-router pro but I don't know why background being extracted to the parent component helps. It is foreseeable that the extraction would lead to the same background image of all pages in `<Switch>`, which is not the intended effect, thus needing some work on decomposing elements in `<Switch>`.

2022-10-22 00:42 UTC, leo220yuyaodog commented
> @leo220yuyaodog Thanks for reviewing. Yes, the background page reloads while switching between `LoginPage` and `SignupPage`. I'm not a react-router pro but I don't know why background being extracted to the parent component helps. It is foreseeable that the extraction would lead to the same background image of all pages in `<Switch>`, which is not the intended effect.

I don't think about it enough. Fixing the front-end routing bug is probably the best thing to do right now, if it can resolve the problem.

2022-10-22 01:04 UTC, hsluoyz requested changes

2022-10-22 01:04 UTC, hsluoyz commented on web/src/Setting.js
> +export function renderDynamicSignUpLink(application, children) {
All `children` to `text`

2022-10-22 01:04 UTC, hsluoyz commented on web/src/Setting.js
> +      return <Link to={`/signup/${application.name}`}>{children}</Link>;
Extract a function, use `url` as arg

2022-10-22 01:04 UTC, hsluoyz commented on web/src/Setting.js
> +export function renderDynamicSignUpLink(application, children) {
renderSignupLink

2022-10-22 01:04 UTC, hsluoyz commented on web/src/Setting.js
> +export function renderDynamicForgetLink(application, children) {
renderForgetLink

2022-10-22 12:56 UTC, hsluoyz requested changes

2022-10-22 12:56 UTC, hsluoyz commented on web/src/auth/LoginPage.js
> -                    sessionStorage.setItem("signinUrl", window.location.href);
`sessionStorage.setItem("signinUrl", window.location.href);` is missing

2022-10-22 15:17 UTC, hsluoyz approved these changes

2022-10-22 15:17 UTC, merged