feat: add AppName when logging in with DingTalk
casdoor/casdoor pull request #1241
Opened 2022-10-26 09:34 UTC by forestmgy

https://user-images.githubusercontent.com/101162387/197991232-9b42bef2-ce68-40ad-9475-a3b15202b20b.mp4

demo video here

Using the following APIs:
https://open.dingtalk.com/document/orgapp-server/obtain-the-access_token-of-an-internal-app
https://open.dingtalk.com/document/orgapp-server/obtains-the-information-about-the-current-application

2022-10-27 15:14 UTC, hsluoyz commented
@Airkro plz review

2022-10-28 01:39 UTC, Airkro commented
It looks like only fetching the app name and adding it to username. but it is a good start.

What will happen when a DingTalk user doesn't belong to the DingTalk org?

2022-10-28 01:48 UTC, forestmgy commented
@Airkro I got it, let me try again

2022-10-28 06:50 UTC, hsluoyz requested changes

2022-10-28 06:50 UTC, hsluoyz commented on idp/dingtalk.go
> +	jsonData := v.(map[string]interface{})
Dump JSON data into struct

2022-10-28 14:13 UTC, hsluoyz approved these changes

2022-10-28 14:14 UTC, merged