fix: jump back to the login page after resetting password
casdoor/casdoor pull request #1288
Opened 2022-11-12 01:19 UTC by imchell

Fix: #1272 

Original codes failed because:

1. `redirectToLoginPage()` was called in class components which is not compatible with react hooks (`useHistory()` in this case). `redirectToLoginPage()` now uses naive JS implementation of redirecting.
2. `path.join(application.homepageUrl, "login")` returns `login` instead of `/login`.

2022-11-12 16:07 UTC, hsluoyz commented
@leo220yuyaodog plz review

2022-11-13 01:58 UTC, hsluoyz requested changes

2022-11-13 01:58 UTC, hsluoyz commented on web/src/Setting.js
> +  window.location.replace(loginLink);
Why switch to hard-routing? Will it cause full page reload? This is not good

2022-11-13 03:25 UTC, hsluoyz approved these changes

2022-11-13 04:16 UTC, merged

2022-11-13 04:20 UTC, leo220yuyaodog commented on web/src/auth/ForgetPage.js
> +        Setting.redirectToLoginPage(this.state.application, this.props.history);
If set password successfully, when I use the account to login. Show errer message
sign out before login. Maybe can redirect to the home page.