feat: manager applications in organization scope
casdoor/casdoor pull request #1290
Opened 2022-11-12 04:47 UTC by leo220yuyaodog

2022-11-13 07:24 UTC, hsluoyz requested changes

2022-11-13 07:24 UTC, hsluoyz commented on object/application_item.go
> +	var res []*ProviderItem
Will this work on zero length?

2022-11-13 07:24 UTC, hsluoyz commented on object/token.go
> +	provider := GetProviderByName(mpProvider.Name)
Why change this?

2022-11-13 07:24 UTC, hsluoyz commented on object/provider_item.go
> +	Owner     string    `json:"owner"`
Before name

2022-11-13 07:24 UTC, hsluoyz commented on authz/authz.go
> +	if user != nil && user.IsAdmin && (subOwner == objOwner || (objOwner == "admin")) {
Don't allow now

2022-11-13 07:24 UTC, hsluoyz commented on web/src/App.js
> +          <Route exact path="/providers/:owner/:providerName" render={(props) => this.renderLoginIfNotLoggedIn(<ProviderEditPage account={this.state.account} {...props} />)} />
owner --> organizationName

2022-11-13 07:24 UTC, hsluoyz commented on web/src/backend/ProviderBackend.js
> +export function getAdminAndOrganizationProviders(organization) {
We don't need `getAdminAndOrganizationProviders`

2022-11-13 07:24 UTC, hsluoyz commented on web/src/ApplicationListPage.js
> +      formOffset: 2,
Why change CSS?

2022-11-13 07:24 UTC, hsluoyz commented on web/src/ApplicationListPage.js
> +  }
new line

2022-11-14 11:03 UTC, leo220yuyaodog commented
@hsluoyz  plz review

2022-11-19 15:00 UTC, hsluoyz requested changes

2022-11-20 17:17 UTC, hsluoyz approved these changes

2022-11-20 17:17 UTC, merged