feat: User Profile Properties can't edit
casdoor/casdoor pull request #1404
Opened 2022-12-16 11:12 UTC by jakiuncle

feat: User Profile Properties can't edit

2022-12-16 11:16 UTC, jakiuncle commented
draft

2022-12-18 14:40 UTC, hsluoyz commented
@leo220yuyaodog plz review

2022-12-18 15:01 UTC, leo220yuyaodog reviewed
Lgtm. Can add some i18 translate.

2022-12-18 15:01 UTC, leo220yuyaodog commented on web/src/common/PropertyTable.js
> +              <Tooltip placement="topLeft" title="Edit">
```suggestion
              <Tooltip placement="topLeft" title={i18next.t("general:Edit")}>
```

2022-12-18 15:01 UTC, leo220yuyaodog commented on web/src/common/PropertyTable.js
> +              <Tooltip placement="topLeft" title="Delete">
```suggestion
              <Tooltip placement="topLeft" title={i18next.t("general:Delete")}>
```

2022-12-19 05:00 UTC, leo220yuyaodog approved these changes

2022-12-19 05:06 UTC, hsluoyz commented
@leo220yuyaodog

2022-12-19 05:07 UTC, hsluoyz commented
@jakiuncle provide a demo video

2022-12-19 05:16 UTC, jakiuncle commented
https://user-images.githubusercontent.com/88994283/208352868-7a03fb35-b7e5-4bba-9c09-ea1c5bf00068.MP4

2022-12-19 10:32 UTC, jakiuncle commented
@hsluoyz plz review

2022-12-21 10:40 UTC, jakiuncle commented
https://user-images.githubusercontent.com/88994283/208886063-81c16bce-bbfd-401b-90de-3f7fe86e2f37.mp4

2022-12-21 15:24 UTC, hsluoyz requested changes

2022-12-21 15:24 UTC, hsluoyz commented on web/src/UserEditPage.js
> +import PropertyTable from "./common/PropertyTable";
import PropertyTable from "./PropertyTable";

2022-12-21 15:24 UTC, hsluoyz commented on web/src/UserEditPage.js
>  import "codemirror/lib/codemirror.css";
these 3 lines?

2022-12-21 15:24 UTC, hsluoyz commented on web/src/UserEditPage.js
> +    if (["properties"].includes(key)) {
What's this?

2022-12-21 15:24 UTC, hsluoyz commented on web/src/common/PropertyTable.js
> +class PolicyTable extends React.Component {
PropertyTable

2022-12-21 15:24 UTC, hsluoyz commented on web/src/common/PropertyTable.js
> +      const property = new Object();
?

2022-12-21 15:24 UTC, hsluoyz commented on web/src/common/PropertyTable.js
> +    table = Setting.addRow(table, row, "top");
top?

2022-12-21 15:24 UTC, hsluoyz commented on web/src/common/PropertyTable.js
> +        title: "Keys",
i18n?

2022-12-21 15:24 UTC, hsluoyz commented on web/src/common/PropertyTable.js
> +        title: "Values",
i18n?

2022-12-21 15:24 UTC, hsluoyz commented on web/src/common/PropertyTable.js
> +    return (<>
<>?

2022-12-22 02:08 UTC, closed without merging