fix: destroy session after delete user
casdoor/casdoor pull request #1441
Opened 2023-01-02 11:03 UTC by leo220yuyaodog

2023-01-02 13:59 UTC, hsluoyz requested changes

2023-01-02 13:59 UTC, hsluoyz commented on object/userSession.go
> +type userSession struct {
Session

2023-01-05 02:08 UTC, leo220yuyaodog commented
delete user:

https://user-images.githubusercontent.com/71440988/210685476-fcef02a9-b411-43f7-b600-8ffa1b0a9622.mp4

offline user:

https://user-images.githubusercontent.com/71440988/210685493-5f486aad-8c35-4ad5-b03e-0a54de72af81.mp4

2023-01-05 07:51 UTC, leo220yuyaodog commented
https://user-images.githubusercontent.com/71440988/210728802-38d5b497-ef86-4d28-a243-c38e71bf4981.mp4

2023-01-05 11:30 UTC, hsluoyz approved these changes

2023-01-06 07:04 UTC, merged