Update Tooltips
casdoor/casdoor pull request #1459
Opened 2023-01-09 18:43 UTC by Xhy-5000

2023-01-09 18:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/casdoor/casdoor?pullRequest=1459) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/casdoor/casdoor?pullRequest=1459) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/casdoor/casdoor?pullRequest=1459) it.</sub>

2023-01-10 05:59 UTC, hsluoyz commented
@imchell plz review

2023-01-10 08:53 UTC, imchell commented on web/src/locales/en/data.json
> +    "Background URL - Tooltip": "Login page background image URL",
It is not only the login page background (but also sign up page, etc.)

2023-01-10 08:53 UTC, imchell commented on web/src/locales/en/data.json
> +    "Provider - Tooltip": "Provider that need to be configured for third-party login",
Grammatical mistake

2023-01-10 08:53 UTC, imchell commented on web/src/locales/en/data.json
> +    "State - Tooltip": "Statep",
Not sure what Statep means, is that a typo?

2023-01-10 08:53 UTC, imchell commented on web/src/locales/en/data.json
> +    "Auto Sync - Tooltip": "Automatic synchronization configuration, disabled when 0",
synchronization configuration -> configuration synchronization

2023-01-10 10:40 UTC, hsluoyz requested changes

2023-01-10 10:40 UTC, hsluoyz commented on web/src/locales/en/data.json
>      "Failed to sync policies": "Failed to sync policies",
Update zh too

2023-01-12 08:05 UTC, hsluoyz commented
@Xhy-5000 fix conflicts

![image](https://user-images.githubusercontent.com/3787410/212011563-217a267b-0383-47eb-a088-f7e6a78e4f00.png)

2023-01-12 21:27 UTC, closed without merging

2023-01-13 01:50 UTC, hsluoyz commented
Replaced by: https://github.com/casdoor/casdoor/pull/1475