fix: Inconsistent translation format for tooltips
casdoor/casdoor pull request #1475
Opened 2023-01-12 21:33 UTC by Xhy-5000

Fix: https://github.com/casdoor/casdoor/issues/1309

2023-01-13 03:07 UTC, hsluoyz commented
@imchell plz review

2023-01-13 11:37 UTC, imchell commented
You can update **all** i18n data with [one command](https://casdoor.org/docs/contributing#how-to-update-i18n-data) so that you do not have to add translation entries to different `json` files in `web/src/locales/` manually.

2023-01-14 23:41 UTC, Xhy-5000 commented
> 
Oh I see that, thx.

2023-01-27 02:32 UTC, hsluoyz requested changes

2023-01-27 02:32 UTC, hsluoyz commented on web/src/locales/en/data.json
> +    "Category - Tooltip": "Category",
Don't just remove `- Tooltip` as final text

2023-03-30 11:50 UTC, closed without merging