fix: update permission rule when role updated
casdoor/casdoor pull request #1477
Opened 2023-01-14 11:39 UTC by notdu

2023-01-14 11:43 UTC, notdu commented
continue the PR #1153

2023-01-14 11:59 UTC, hsluoyz commented
@leo220yuyaodog plz review

2023-01-14 11:59 UTC, hsluoyz requested changes

2023-01-14 11:59 UTC, hsluoyz commented on object/permission_enforcer.go
> +					groupingPolicies = append(groupingPolicies, []string{subUser, domain, role, "", "", permissionID})
Use `permissionId`

2023-01-14 15:43 UTC, hsluoyz approved these changes

2023-01-15 04:06 UTC, hsluoyz commented
@notdu plz fix conflicts

![image](https://user-images.githubusercontent.com/3787410/212522432-88a0167b-1659-41d0-aa5b-11057f8749b8.png)

2023-01-15 06:18 UTC, leo220yuyaodog commented
Need to do some compatiable, like these pr #1478 
If use rbac model, the table permission_rule will has g type policy 
![image](https://user-images.githubusercontent.com/71440988/212525819-c3dce0f9-6acd-4703-a016-6490892ef2e2.png)
But if other permission use models that do not have `[role_definition]`, it will cause when init enforce.
![image](https://user-images.githubusercontent.com/71440988/212526007-618a3de2-a624-4907-873a-435c48bf7480.png)

See the image, the model don't has g type
![image](https://user-images.githubusercontent.com/71440988/212525914-a0fe4d6f-845e-4b25-9c57-1af70a799d47.png)

2023-01-15 11:07 UTC, notdu commented
Hi @hsluoyz, @leo220yuyaodog,
In Casbin, we don't check if the `assertion` is exist or not when `LoadPolicyArray`, is it ok if i create a PR to fix it.
The problem above will be solved.
<img width="2625" alt="Screenshot 2023-01-15 at 6 05 21 PM" src="https://user-images.githubusercontent.com/55494127/212537136-8cbd9961-ebeb-4894-bece-b80e8ab55743.png">

2023-01-15 15:18 UTC, hsluoyz commented
@notdu if the Casbin model is not a RBAC enabled model, then all `g` rules should be ignored (not loaded into the enforcer)

2023-01-15 16:21 UTC, notdu commented
@hsluoyz by adding 
` if assertion := m[sec][key]; assertion == nil { 
	return nil
}`
to `LoadPolicyArray` 
i think we can handle it, or anything wrong with my solution?

2023-01-15 16:30 UTC, hsluoyz commented
@notdu it seems to be OK. Can you update the PR so I can see the whole code?

2023-01-15 17:31 UTC, notdu commented
@hsluoyz Nothing change on this PR, i'll create a PR on casbin, after that PR is merged, i'll update this PR

2023-01-16 00:43 UTC, hsluoyz commented
@notdu the whole change should happen in this repo. Casbin side is not needed to be changed.

2023-01-16 07:59 UTC, leo220yuyaodog commented
> @hsluoyz by adding ` if assertion := m[sec][key]; assertion == nil { return nil }` to `LoadPolicyArray` i think we can handle it, or anything wrong with my solution?

https://github.com/casdoor/casdoor/blob/d0741e37057283c67e8f13e4db44b0609f32e8ad/object/permission_enforcer.go#L53
Can add the condition to filter policy of the adapter according to the model text before use the adapter to init the enforce.
```go
if !strings.Contains(permissionModel.ModelText,"[role_definition]"){
	adapter.LoadFilteredPolicy(m, xormadapter.Filter{Ptype: []string{"p"}})
}
```

2023-01-16 08:01 UTC, notdu commented
@leo220yuyaodog, @hsluoyz 
plz review my new updates

2023-01-17 02:04 UTC, leo220yuyaodog commented
> @leo220yuyaodog, @hsluoyz plz review my new updates

lgtm

2023-01-17 02:27 UTC, merged