refactor: updateOrganization panic err to return err
casdoor/casdoor pull request #1836
Opened 2023-05-14 15:54 UTC by yehong-z

2023-05-15 00:52 UTC, hsluoyz requested changes

2023-05-15 00:52 UTC, hsluoyz commented on object/organization.go
> +		return false, nil
return i18n error: `The object does not exist: org_id`

2023-05-15 00:52 UTC, hsluoyz commented on controllers/organization.go
> +		c.Data["json"] = wrapActionResponse(affected)
Add `wrapActionResponse2(affected, err)`

2023-05-15 00:53 UTC, hsluoyz requested changes

2023-05-15 00:53 UTC, hsluoyz commented on controllers/organization.go
>  		c.ResponseError(err.Error())
All `panic(err)` in `organization.go` first, then for all files

2023-05-15 16:38 UTC, yehong-z commented
将organization中的panic改为了返回err的形式
影响的到controller层函数加上了
if err != nil {
    c.responseError()
}
影响到的其他model层暂时用以下形式改动
result, _ := func()
以保证代码能够运行。

2023-05-19 06:31 UTC, hsluoyz requested changes

2023-05-19 06:31 UTC, hsluoyz commented on controllers/account.go
> +	organization, err := object.GetOrganization(fmt.Sprintf("%s/%s", "admin", authForm.Organization))
util.GetId

2023-05-19 06:31 UTC, hsluoyz commented on controllers/auth.go
> +		organization, err := object.GetOrganization(fmt.Sprintf("%s/%s", "admin", application.Organization))
util.GetId

2023-05-19 06:31 UTC, hsluoyz commented on object/organization.go
> +func GetOrganizationCount(owner, field, value string) (count int64, err error) {
int

2023-05-19 06:31 UTC, hsluoyz commented on object/organization.go
> +		return nil, fmt.Errorf("check:Organization does not exist")
owner or name is empty

2023-05-19 06:31 UTC, hsluoyz commented on object/organization.go
> +	return nil, fmt.Errorf("check:Organization does not exist")
Object does not exist

2023-05-19 06:31 UTC, hsluoyz commented on object/organization.go
> +	affectedRows, err := adapter.Engine.Insert(organization)
affected

2023-05-19 06:31 UTC, hsluoyz commented on object/organization.go
> +	affectedRows, err := adapter.Engine.ID(core.PK{organization.Owner, organization.Name}).Delete(&Organization{})
affected

2023-05-19 06:31 UTC, hsluoyz commented on object/organization.go
> +		return false, fmt.Errorf("Cannot delete built-in organization")
prefix

2023-05-19 08:28 UTC, hsluoyz requested changes

2023-05-19 08:28 UTC, hsluoyz commented on controllers/account.go
> -	organization := object.GetMaskedOrganization(object.GetOrganizationByUser(user))
What about `GetMaskedOrganization` accept 2nd arg of error?

2023-05-19 08:28 UTC, hsluoyz commented on controllers/account.go
> +		c.ResponseError(c.T(err.Error()))
c.T will work for DB errors?

2023-05-19 08:28 UTC, hsluoyz commented on controllers/organization.go
> -	c.Data["json"] = wrapActionResponse(object.AddOrganization(&organization))
wrapActionResponse accepts new error arg

2023-05-21 15:41 UTC, hsluoyz requested changes

2023-05-21 15:41 UTC, hsluoyz commented on controllers/organization.go
> +	c.Data["json"], _ = object.GetMaskedOrganization(object.GetOrganization(id))
panic

2023-05-21 15:41 UTC, hsluoyz commented on ldap/util.go
> +		organization, _ := object.GetOrganization(util.GetId("admin", org))
panic

2023-05-21 15:41 UTC, hsluoyz commented on ldap/util.go
> +	org, _ := object.GetOrganizationByUser(user)
panic

2023-05-21 15:41 UTC, hsluoyz commented on object/application.go
> +	organization, _ := getOrganization(application.Owner, application.Organization)
panic

2023-05-21 15:41 UTC, hsluoyz commented on object/check.go
> +	organization, _ := GetOrganizationByUser(user)
panic

2023-05-21 15:41 UTC, hsluoyz commented on object/init.go
> +	organization, _ := getOrganization("admin", "built-in")
panic

2023-05-21 15:41 UTC, hsluoyz commented on object/init_data.go
> +	existed, _ := getOrganization(organization.Owner, organization.Name)
panic

2023-05-21 15:41 UTC, hsluoyz commented on object/ldap_conn.go
> +	organization, _ := getOrganization("admin", owner)
panic

2023-05-28 10:33 UTC, hsluoyz approved these changes

2023-05-30 07:49 UTC, merged