feat: Support Telegram Notification provider
casdoor/casdoor pull request #2225
Opened 2023-08-18 06:29 UTC by UsherFall

#1382

2023-08-18 07:17 UTC, hsluoyz requested changes

2023-08-18 07:17 UTC, hsluoyz commented on web/src/common/TestNotificationWidget.js
> +        Setting.showMessage("success", `${i18next.t("provider:Notification sent successfully")}`);
i18n

2023-08-18 07:17 UTC, hsluoyz commented on object/notification.go
> +import (
linter

2023-08-18 13:42 UTC, UsherFall commented
https://github.com/casdoor/casdoor/assets/98513748/06707505-5af4-4963-bd0b-294c5f78f9fb

2023-08-19 04:32 UTC, hsluoyz approved these changes

2023-08-19 04:33 UTC, merged