Feat: support subscription mode(year/month)
casdoor/casdoor pull request #2265
Opened 2023-08-28 05:28 UTC by Chinoholo0807

2023-08-28 05:31 UTC, Chinoholo0807 commented
https://github.com/casdoor/casdoor/assets/54203997/961e0cf2-6ed5-44a8-a225-8203adad2708

2023-08-28 10:16 UTC, hsluoyz commented on web/src/pricing/PricingPage.js
> +              {/* <Row style={{justifyContent: "center"}}>
Don't remove trial

2023-08-28 10:18 UTC, hsluoyz commented on web/src/pricing/SingleCard.js
> +                    <span style={{fontSize: "40px", fontWeight: 700}}>{Setting.getCurrencySymbol(plan.currency)} {plan.pricePerMonth}</span>
`{mode === "month" ? plan.pricePerMonth : plan.pricePerYear}`

2023-08-28 10:19 UTC, hsluoyz commented on web/src/pricing/PricingPage.js
> +  async loadPricing(pricingName) {
Why add async?

2023-08-28 10:22 UTC, hsluoyz commented on object/pricing.go
> +	Modes         []string `json:"modes"`
`Mode string`

Three options:

“Monthly”, "Yearly", "Monthly and Yearly"

2023-08-28 10:23 UTC, hsluoyz commented on web/src/PricingEditPage.js
> +              options={[{label: "Monthly", value: "month"}, {label: "Yearly", value: "year"}]}
{label: "Monthly", value: "Monthly"}, {label: "Yearly", value: "Yearly"}

2023-08-28 10:28 UTC, hsluoyz commented on object/plan.go
> +	ProductMonth     string   `xorm:"'product'" json:"productMonth"`        // related product id (sub mode is month)
ProductMonthly, remove comment

2023-08-28 15:48 UTC, Chinoholo0807 commented on web/src/pricing/PricingPage.js
> +  async loadPricing(pricingName) {
use await in function

2023-08-28 15:58 UTC, Chinoholo0807 commented
https://github.com/casdoor/casdoor/assets/54203997/1be05f53-b387-4791-999b-c39149a1a015

2023-08-28 16:52 UTC, hsluoyz requested changes

2023-08-28 16:52 UTC, hsluoyz commented on object/pricing.go
> +type Period string
Just string

2023-08-28 16:52 UTC, hsluoyz commented on web/src/pricing/SingleCard.js
> +                  period === "Monthly" ? (
Can't you write this way?

```react
<>
  <span style={{fontSize: "40px", fontWeight: 700}}>{Setting.getCurrencySymbol(plan.currency)} {period === "Monthly" ? plan.pricePerMonth : plan.pricePerYearly}</span>
    <span style={{fontSize: "18px", fontWeight: 600, color: "gray"}}>  {i18next.t("plan:per month")}</span>
  </>
```

2023-08-28 16:52 UTC, hsluoyz commented on web/src/pricing/PricingPage.js
> +                  <SingleCard
Don't change unrelated things

2023-08-28 16:52 UTC, hsluoyz commented on object/plan.go
> +	ProductMonth     string   `xorm:"'product'" json:"productMonth"`
Remove ProductMonth and ProductYear, add `Period` as string

2023-08-28 16:52 UTC, hsluoyz commented on object/pricing.go
> +	BillingPeriods []Period `json:"billingPeriods"`
Remove `BillingPeriods`

2023-08-28 16:52 UTC, hsluoyz commented on object/product.go
> +func BuyProduct(id string, user *User, providerName, pricingName, planName, host string, period Period) (string, string, error) {
Don't add `period` as arg everywhere, it's not that important

2023-08-28 17:14 UTC, hsluoyz requested changes

2023-08-28 17:14 UTC, hsluoyz commented on object/subscription.go
>  		Plan:    planName,
Subscription doesn't need to know pricing?

2023-08-28 17:14 UTC, hsluoyz commented on object/subscription.go
> +		Duration:  duration,
Duration and Period are duplicated, keep `Period`

2023-08-28 17:14 UTC, hsluoyz commented on web/src/PricingEditPage.js
> +          <Col style={{marginTop: "5px"}} span={(Setting.isMobile()) ? 22 : 2}>
Remove

2023-08-28 17:14 UTC, hsluoyz commented on web/src/Setting.js
> +export function getValidArray(array, defaultValue) {
Remove

2023-08-28 17:14 UTC, hsluoyz commented on web/src/auth/SignupPage.js
> +      return `/buy-plan/${application.organization}/${signupParams?.pricing}?user=${signupParams.username}&plan=${signupParams.plan}&period=${signupParams.period}`;
Remove

2023-08-28 17:14 UTC, hsluoyz commented on web/src/pricing/PricingPage.js
> +      const res = await PricingBackend.getPricing(this.state.owner, pricingName);
Why not use callback?

2023-08-28 17:14 UTC, hsluoyz commented on web/src/pricing/PricingPage.js
> +        throw new Error(res.msg);
Why change to throw? Throw to console?

2023-08-28 17:18 UTC, hsluoyz commented
@Chinoholo0807 fix:

![image](https://github.com/casdoor/casdoor/assets/3787410/cdb150ff-029d-46b0-8c3b-1ac6b1942bc9)

2023-08-30 07:21 UTC, Chinoholo0807 commented
Uploading 2023-08-30_15-06-02.mp4…

2023-08-30 09:13 UTC, merged