feat: add DoubleMd5UserSaltCredManager
casdoor/casdoor pull request #2833
Opened 2024-03-22 09:54 UTC by luliangce

When I migrated the user system from an old service to Casdoor and synchronized the users, I found that there was no suitable password algorithm. This algorithm may be relatively obscure, but I hope to add it to the Casdoor.

2024-03-22 09:54 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/casdoor/casdoor?pullRequest=2833) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/casdoor/casdoor?pullRequest=2833) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/casdoor/casdoor?pullRequest=2833) it.</sub>

2024-03-22 12:10 UTC, hsluoyz commented
@luliangce can you share which famous systems or services use this? Like: https://casdoor.org/docs/organization/overview/

![image](https://github.com/casdoor/casdoor/assets/3787410/4aea1a7e-eff7-40ff-b48a-fe0418be9612)

2024-03-22 12:11 UTC, hsluoyz requested changes

2024-03-22 12:11 UTC, hsluoyz commented on cred/manager.go
> +	} else if passwordType == "double-md5-salt" {
Put after "md5-salt"

2024-03-22 12:11 UTC, hsluoyz commented on web/src/OrganizationEditPage.js
> +              options={["plain", "salt", "sha512-salt", "md5-salt", "bcrypt", "pbkdf2-salt", "argon2id", "double-md5-salt"].map(item => Setting.getOption(item, item))}
Put after "md5-salt"

2024-03-27 15:23 UTC, hsluoyz commented
@luliangce any update?

2024-03-28 01:59 UTC, luliangce commented
> @luliangce can you share which famous systems or services use this? Like: https://casdoor.org/docs/organization/overview/
> 
> ![image](https://private-user-images.githubusercontent.com/3787410/316002917-4aea1a7e-eff7-40ff-b48a-fe0418be9612.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1OTA4MDcsIm5iZiI6MTcxMTU5MDUwNywicGF0aCI6Ii8zNzg3NDEwLzMxNjAwMjkxNy00YWVhMWE3ZS1lZmY3LTQwZmYtYjQ4YS1mZTA0MThiZTk2MTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjhUMDE0ODI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTA3NTQ2YmJhZTFkZGQyODc0MWY1NDAxYmQ3YjA0MmE3OTc2MGQ4NjdhNGYyMmJlYmFkNjNmMjdlZDgwMThjMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.0RI6PZ_HJ5_onp7gCWv4EbmXLtTnZyP-mjPLuovHYKw)

After thinking it over again, I don't think any popular services are using this, so I've decided this change isn't really  good  for merging into casdoor.

2024-03-28 01:59 UTC, closed without merging