feat: Add Google token props to user's properties
casdoor/casdoor pull request #2999
Opened 2024-06-06 11:20 UTC by Sesota

Enables casdoor to store google credentials (access_token, refresh_token, etc.) in user properties attributes after a successful "Sign up/in with google". 

Useful for when application needs to call Google APIs on behalf of the user.

2024-06-06 11:20 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/casdoor/casdoor?pullRequest=2999) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/casdoor/casdoor?pullRequest=2999) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/casdoor/casdoor?pullRequest=2999) it.</sub>

2024-06-06 12:18 UTC, hsluoyz requested changes

2024-06-06 12:18 UTC, hsluoyz commented on controllers/auth.go
> +			if userInfo.Extra == nil {
Add the code to your google only, don't mess with other providers

2024-06-19 10:21 UTC, hsluoyz approved these changes

2024-06-19 10:24 UTC, hsluoyz commented
@Sesota fix all errors

2024-06-19 15:50 UTC, Sesota commented
> @Sesota fix all errors

Fixed @hsluoyz

2024-06-19 16:19 UTC, hsluoyz commented
@Sesota sign CLA

![image](https://github.com/casdoor/casdoor/assets/3787410/4e946dfa-4e1c-4efa-97b3-c00a373cb585)

2024-06-21 12:19 UTC, closed without merging