feat: integrate external model editor and handle message events for model updates
casdoor/casdoor pull request #3176
Opened 2024-09-06 07:06 UTC by HashCookie

2024-09-08 03:45 UTC, HashCookie commented
https://github.com/user-attachments/assets/a417f823-8051-46ff-8d5a-881619bacdd2

2024-09-16 13:16 UTC, hsluoyz requested changes

2024-09-16 13:16 UTC, hsluoyz commented on web/src/ModelEditPage.js
> +  submitModelEdit(exitAfterSave) {
Why move position? You lost the git diff

2024-09-16 13:16 UTC, hsluoyz commented on web/src/IframeEditor.js
> +import React, {forwardRef, useEffect, useImperativeHandle, useRef, useState} from "react";
Apache header, note year is 2024

2024-09-16 13:16 UTC, hsluoyz commented on web/src/CasbinEditor.js
> +import React, {useCallback, useEffect, useRef, useState} from "react";
Apache header, note year is 2024

2024-09-16 13:16 UTC, hsluoyz commented on web/src/index.css
> +.full-height-editor {
Don't affect other codemirror usage in Casdoor frontend

2024-09-16 14:19 UTC, hsluoyz approved these changes

2024-09-16 14:25 UTC, merged