feat: update captcha rule when the login page component is mounted
casdoor/casdoor pull request #3281
Opened 2024-10-11 13:33 UTC by ZhaoYP-2001

fix: https://github.com/casdoor/casdoor/issues/3279

2024-10-11 13:43 UTC, hsluoyz requested changes

2024-10-11 13:43 UTC, hsluoyz commented on web/src/auth/LoginPage.js
> +        this.setState({enableCaptchaModal: CaptchaRule.Always});
Why is `enableCaptchaModal` a React state from the beginning? Shouldn't it be a direct assignment like `this.getCaptchaRule(this.props.application);`?

2024-10-11 15:41 UTC, hsluoyz commented
@dacongda plz review

2024-10-11 16:03 UTC, dacongda approved these changes

2024-10-12 02:02 UTC, hsluoyz approved these changes

2024-10-12 02:02 UTC, merged