feat: Adding contents of memberOf fields with connecting via LDAP
casdoor/casdoor pull request #3341
Opened 2024-11-08 14:10 UTC by ysirotinskii

Hi, could you please look at the PR, the fixes include the addition and aggregation of MemberOf elements, which we receive from an external LDAP server

Looking forward to PR approval

2024-11-08 14:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/casdoor/casdoor?pullRequest=3341) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/casdoor/casdoor?pullRequest=3341) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/casdoor/casdoor?pullRequest=3341) it.</sub>

2024-11-08 14:33 UTC, hsluoyz commented
@ysirotinskii first pass all CIs, it will not go to review stage before you pass all CIs

2024-11-09 01:23 UTC, hsluoyz requested changes

2024-11-09 01:23 UTC, hsluoyz commented on object/ldap_conn.go
> +				fmt.Printf("Synchronized user %s: %v\n", user, attribute.Values)
Don't print to console

2024-11-09 01:23 UTC, hsluoyz commented on object/user.go
> +	Member      []string `json:"member"`
You should not add new field. What's member? Is it the groups the user belongs to? We already have groups field

2024-11-11 08:40 UTC, dacongda commented
after research, memberOf seems to be a optional module of ldap and it can be used to find the group via user, I don't think it can be a independence field of user.

2024-11-11 09:24 UTC, closed without merging

2024-11-11 09:24 UTC, hsluoyz commented
@ysirotinskii like @dacongda said, the problem you are trying to resolve is meaningful. But your code quality is below the bar. It needs a more skilled person to do the job and make the PR. So closed here for now.