feat: Force users to change their passwords after 3/6/12 months
casdoor/casdoor pull request #3352
Opened 2024-11-16 02:19 UTC by ljl66-66

2024-11-16 05:39 UTC, ljl66-66 commented
source of issue：[#issue3330](https://github.com/casdoor/casdoor/issues/3330)

2024-11-16 07:48 UTC, hsluoyz requested changes

2024-11-16 07:48 UTC, hsluoyz commented on object/check.go
> +		return nil, fmt.Errorf(i18n.Translate(lang, "check:Your password has not been changed for too long, please click Forgot Password to change your password"))
use ChatGPT, don't write English text by yourself

2024-11-16 07:48 UTC, hsluoyz commented on object/check.go
>  			return nil, err
Check in non-LDAP path

2024-11-16 07:48 UTC, hsluoyz commented on object/check.go
> +		user.NeedUpdatePassword = true
Don't mess with NeedUpdatePassword if you don't fully understand and know how to use it

2024-11-16 07:48 UTC, hsluoyz commented on object/check_password_expired.go
> +func CheckPasswordExpired(user *User) bool {
C -> c

2024-11-16 07:48 UTC, hsluoyz commented on object/check_password_expired.go
> +	lastChangeTime, err := getLastTimeOfAction(organization.Name, user.Name, "set-password")
Add a field to user to record the last password change time, don't iterate on logs

2024-11-16 08:22 UTC, hsluoyz requested changes

2024-11-16 08:22 UTC, hsluoyz commented on object/check.go
> +		UpdateUser(user.GetId(), user, []string{"need_update_password"}, false)
We handle all errors returned by UpdateUser

2024-11-19 06:38 UTC, hsluoyz commented on object/user.go
> +	LastChangePasswordTime string           `xorm:"varchar(100)" json:"lastChangePasswordTime"`
Put before LastSigninWrongTime

2024-11-19 06:38 UTC, hsluoyz commented on object/user.go
> +			"yammer", "yandex", "zoom", "custom", "need_update_password", "ip_whitelist", "last_change_password_time",
Put before LastSigninWrongTime

2024-11-19 06:38 UTC, hsluoyz commented on web/src/UserEditPage.js
> +            {Setting.getLabel(i18next.t("user:Last change password time"), i18next.t("user:Last change password time"))} :
Put before LastSigninWrongTime

2024-11-19 06:39 UTC, hsluoyz commented on controllers/user.go
> +	targetUser.LastChangePasswordTime = time.Now().Format(time.RFC3339)
use util.GetCurrentTime

2024-11-19 06:40 UTC, hsluoyz commented on object/check_password_expired.go
> +func checkPasswordExpired(user *User) bool {
return error like CheckPassword

2024-11-19 06:40 UTC, hsluoyz commented on object/check_password_expired.go
> +	}
check nil for organization

2024-11-19 06:41 UTC, hsluoyz commented on object/check_password_expired.go
> +package object
Apache header

2024-11-19 06:44 UTC, hsluoyz commented on object/check_password_expired.go
> +		return false
If I didn't ever change password, I can bypass this check, is this OK? It's a security hole!

You should use user created time if lastChangePasswordTime is empty

If user created time is also empty, then return error

2024-11-19 10:25 UTC, hsluoyz requested changes

2024-11-19 10:25 UTC, hsluoyz commented on object/check_password_expired.go
>  	expiryDate := lastTime.AddDate(0, 0, passwordExpireDays)
expiryDate -> expireTime

2024-11-19 13:06 UTC, merged