Add loading and countdown status to the verification code sending button
casdoor/casdoor pull request #384
Opened 2021-12-21 05:00 UTC by jianmaikj

2021-12-21 11:42 UTC, Steve0x2a commented
This pr looks good, but seems to contain code for https://github.com/casbin/casdoor/pull/386

2021-12-21 11:48 UTC, solo-xwz commented
> This pr looks good, but seems to contain code for #386

Indeed, I reverted that changes

2021-12-21 11:48 UTC, jianmaikj commented
> This pr looks good, but seems to contain code for #386

Indeed, I reverted that changes

2021-12-21 12:36 UTC, Steve0x2a reviewed
lgtm

2021-12-21 13:01 UTC, seriouszyx commented
Please fix. 

- [You have 3 commits incorrectly signed off.](https://github.com/casbin/casdoor/pull/384/checks?check_run_id=4594343165)
- Rename the PR title and commit message with conventions such as [Angular](https://www.conventionalcommits.org/en/v1.0.0/#examples).

![image](https://user-images.githubusercontent.com/33992371/146934229-52b1c294-017c-4835-a9e5-4541c1ff1315.png)

2021-12-21 16:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/casdoor/casdoor?pullRequest=384) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/casdoor/casdoor?pullRequest=384) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/casdoor/casdoor?pullRequest=384) it.</sub>

2021-12-22 14:02 UTC, hsluoyz requested changes

2021-12-22 14:02 UTC, hsluoyz commented on web/src/component/CountDownInput.js
> +        <Col>
Don't change the 2-space indentation.

2021-12-22 14:02 UTC, hsluoyz commented on web/src/component/CountDownInput.js
> +            addonBefore={textBefore}
Don't change the 2-space indentation.

2021-12-23 00:39 UTC, jianmaikj commented on web/src/component/CountDownInput.js
> +            addonBefore={textBefore}
fixed

2021-12-23 01:36 UTC, hsluoyz approved these changes

2021-12-23 01:38 UTC, hsluoyz commented
@jianmaikj plz fix:

![image](https://user-images.githubusercontent.com/3787410/147174506-983ecd0e-07f2-4624-a17f-5ca05842886d.png)

2021-12-23 11:41 UTC, merged