fix: fix the SQL injection vulnerability in field filter
casdoor/casdoor pull request #442
Opened 2022-01-23 16:11 UTC by seriouszyx

Signed-off-by: Yixiang Zhao <seriouszyx@foxmail.com>

#439 

Solutions:
1. Use prepared statement
2. Implement the black list to filter the `field`

For the request as below:

```
http://localhost:8000/api/get-organizations?p=1&pageSize=10&value=e99nb&sortField=&sortOrder=&field=(updatexml(1,concat(0x7e,(select%20user()),0x7e),1))%20%20and%20name
```

Before:

![image](https://user-images.githubusercontent.com/33992371/150687435-7dae5f72-ff7e-43b5-adf7-0132b995b341.png)

After:

![image](https://user-images.githubusercontent.com/33992371/150687451-e1c74a07-c056-4a7b-aa1a-643a53f8b6b9.png)

2022-01-23 16:12 UTC, seriouszyx commented
@wuhan005 Please review.

2022-01-23 16:59 UTC, wuhan005 commented
It seems that the blacklist can be bypassed.

Boolean-based blind SQL injection can be used to get the value of the built-in function, the attacker can use functions like `substring` to make a brute-force attack and get each character of the string.

PoC:
```
(substring(user(),1,5) = 'hqcas') <> name
```
* Correct:
![image](https://user-images.githubusercontent.com/12731778/150688688-ee96c4f4-acea-48bd-b9a4-262b1f482464.png)
* Wrong: 
![image](https://user-images.githubusercontent.com/12731778/150688697-3a6d41d7-16cd-462d-9e54-e3492af1dcc2.png)

----
**I think we should use a whitelist instead of the blacklist.**

Maybe we can use `reflect.TypeOf()` to get a struct fields white list easily, here is an example: https://go.dev/play/p/84zUGphgvXR

2022-01-24 05:11 UTC, seriouszyx commented
@wuhan005 Thanks for your advice. I'll fix it.

2022-01-24 14:28 UTC, seriouszyx commented
@wuhan005 Please review the newest commit using whitelists.

2022-01-25 14:51 UTC, hsluoyz requested changes

2022-01-25 14:51 UTC, hsluoyz commented on object/cert.go
>  	certs := []*Cert{}
new line

2022-01-25 14:51 UTC, hsluoyz commented on object/check.go
> +func InitAllowList(i interface{}) map[string]bool {
init

2022-01-25 14:51 UTC, hsluoyz commented on object/check.go
> +}
new line

2022-01-26 07:19 UTC, seriouszyx commented
@wuhan005 Discussed with @hsluoyz, we think the previous implementation was a bit complicated. The `field` only consists of upper and lower case letters and numbers in Casdoor, so we can filter easily. Could you please review the latest commit to check the SQL injection vulnerability?

2022-01-26 08:41 UTC, hsluoyz approved these changes

2022-01-26 09:25 UTC, wuhan005 commented
> @wuhan005 Discussed with @hsluoyz, we think the previous implementation was a bit complicated. The `field` only consists of upper and lower case letters and numbers in Casdoor, so we can filter easily. Could you please review the latest commit to check the SQL injection vulnerability?

There is no SQL injection vulnerability, nicely done.

2022-01-26 11:36 UTC, merged