feat: add casdoor as saml idp support
casdoor/casdoor pull request #571
Opened 2022-03-17 04:04 UTC by Steve0x2a

Now it is necessary to perform sp connection test, so it is set to draft state
Signed-off-by: 0x2a <stevesough@gmail.com>

2022-03-19 12:55 UTC, hsluoyz commented
@seriouszyx plz review

2022-03-20 10:19 UTC, qwqcode commented
nice work!

2022-04-07 05:42 UTC, hsluoyz commented
@seriouszyx plz review

2022-04-07 05:59 UTC, hsluoyz requested changes

2022-04-07 05:59 UTC, hsluoyz commented on web/src/auth/LoginPage.js
> +
no change

2022-04-07 05:59 UTC, hsluoyz commented on web/src/auth/LoginPage.js
> +
no change

2022-04-07 05:59 UTC, hsluoyz commented on web/src/auth/LoginPage.js
> +
no change

2022-04-07 05:59 UTC, hsluoyz commented on web/src/auth/LoginPage.js
> +
no change

2022-04-07 05:59 UTC, hsluoyz commented on web/src/auth/LoginPage.js
> +
no change

2022-04-07 05:59 UTC, hsluoyz commented on web/src/auth/Util.js
>    const nonce = getRefinedValue(queries.get("nonce"))
; for all lines

2022-04-07 05:59 UTC, hsluoyz commented on web/src/auth/AuthCallback.js
> +        const samlRequest = innerParams.get("SAMLRequest");
SAML -> saml

2022-04-07 05:59 UTC, hsluoyz commented on web/src/auth/AuthCallback.js
> +    const samlRequest = innerParams.get("SAMLRequest");
SAML -> saml

2022-04-07 05:59 UTC, hsluoyz commented on web/src/auth/Util.js
> +  const samlRequest = getRefinedValue(queries.get("SAMLRequest"))
SAML -> saml

2022-04-07 05:59 UTC, hsluoyz commented on object/samlidp.go
> +// Copyright 2022 The Casdoor Authors. All Rights Reserved.
this file -> saml_idp.go

saml.go -> saml_sp.go

2022-04-07 05:59 UTC, hsluoyz commented on controllers/saml.go
> +}
new line

2022-04-08 15:06 UTC, hsluoyz approved these changes

2022-04-08 15:06 UTC, merged