Fix comparing hashed password with plain text password during password grant
casdoor/casdoor pull request #627
Opened 2022-03-28 22:59 UTC by mihado

The code is currently comparing the plain text password provided during request with the hashed password of the user.

2022-03-28 22:59 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/casdoor/casdoor?pullRequest=627) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/casdoor/casdoor?pullRequest=627) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/casdoor/casdoor?pullRequest=627) it.</sub>

2022-03-29 02:29 UTC, hsluoyz requested changes

2022-03-29 02:29 UTC, hsluoyz commented on object/token.go
> +		logs.Debug(fmt.Sprintf("GetPasswordToken error: %s", msg))
no log

2022-03-29 02:31 UTC, mihado commented on object/token.go
> +	"github.com/astaxie/beego/logs"
```suggestion
```

2022-03-29 02:31 UTC, mihado commented on object/token.go
> +		logs.Debug(fmt.Sprintf("GetPasswordToken error: %s", msg))
```suggestion
```

2022-03-29 02:33 UTC, mihado commented on object/token.go
> +		logs.Debug(fmt.Sprintf("GetPasswordToken error: %s", msg))
@hsluoyz thanks. updated

2022-03-29 14:40 UTC, hsluoyz approved these changes

2022-03-29 14:40 UTC, hsluoyz commented
@seriouszyx plz review

2022-03-29 14:49 UTC, seriouszyx approved these changes

2022-03-29 16:37 UTC, merged