feat: add enableLimitedAccess setting for accessing user info
casdoor/casdoor pull request #656
Opened 2022-04-09 08:01 UTC by seriouszyx

Fix: #581 

add a organization option `enableLimitedAccess`

![image](https://user-images.githubusercontent.com/33992371/162562526-6fc6abf8-d5a7-4ce1-a6ff-6027a1bb561f.png)

before enabled

![image](https://user-images.githubusercontent.com/33992371/162562558-ba9fb7f3-ee38-41d0-b26d-3c17949b2d3e.png)

after enabled

![image](https://user-images.githubusercontent.com/33992371/162562639-33666322-a3d7-4b82-98ef-09ec6fa00212.png)

Signed-off-by: Yixiang Zhao <seriouszyx@foxmail.com>

2022-04-09 14:12 UTC, hsluoyz requested changes

2022-04-09 14:12 UTC, hsluoyz commented on controllers/user.go
> +	if organization.EnableLimitedAccess {
add `IsProfilePublic` boolean value, true by default

2022-04-09 14:15 UTC, hsluoyz requested changes

2022-04-09 14:15 UTC, hsluoyz commented on object/check.go
> +		} else if targetUser.Owner == requestUser.Owner && requestUser.IsAdmin {
the normal users from the same org should be able to see other's profile.

2022-04-09 14:15 UTC, hsluoyz commented on web/src/OrganizationListPage.js
>    }
Need to add frontend 404 page for other's profile.

2022-04-11 06:10 UTC, hsluoyz requested changes

2022-04-11 06:10 UTC, hsluoyz commented on controllers/user.go
> +	organization := object.GetOrganization(fmt.Sprintf("%s/%s", "admin", strings.Split(id, "/")[0]))
use: GetOwnerAndNameFromId

2022-04-11 06:10 UTC, hsluoyz commented on web/src/UserEditPage.js
> +          window.location.href = "/404";
don't redirect

2022-04-11 06:10 UTC, hsluoyz commented on object/check.go
> +}
new line

2022-04-11 06:10 UTC, hsluoyz commented on controllers/user.go
> +	if organization.IsProfilePublic {
wrong logic?

2022-04-11 12:04 UTC, seriouszyx commented
access user in the same org

![image](https://user-images.githubusercontent.com/33992371/162735436-33c93b08-bde0-4ab0-8ea2-8d98f3dd826c.png)

access user in the different org

![image](https://user-images.githubusercontent.com/33992371/162735536-ec96ac17-766d-448a-b272-47bdb2c7186f.png)

2022-04-16 07:09 UTC, hsluoyz approved these changes

2022-04-16 07:10 UTC, merged