feat: add aliyun captcha
casdoor/casdoor pull request #833
Opened 2022-06-28 13:50 UTC by Resulte

https://user-images.githubusercontent.com/34178764/176194718-0256e1c4-cb83-49fa-bc53-a62170058de9.mov

2022-06-28 15:14 UTC, nomeguy requested changes

2022-06-28 15:14 UTC, nomeguy commented on util/crypto.go
> +func HMACSHA1(keyStr, value string) string {
Use name like `GetHmacSha1`

2022-06-28 15:14 UTC, nomeguy commented on web/src/common/CaptchaPreview.js
> +          (captchaType !== "Default" && (!clientId || !clientSecret)) ||
this logic is too complicated, define `disabled` with multi-line if-else outside of the return.

2022-06-28 15:14 UTC, nomeguy commented on web/src/Setting.js
> +      logo: `${StaticBaseUrl}/img/social_aliyun.png`,
Is this logo there?

2022-06-28 15:14 UTC, nomeguy commented on web/src/ProviderEditPage.js
> +              <Row style={{marginTop: '20px'}} >
clientId2 and clientSecret2 are already in UI?

2022-06-29 03:20 UTC, seriouszyx commented on web/src/common/CountDownInput.js
> -        Setting.showMessage("error", i18next.t("signup:Unknown Check Type"));
if `Setting` is not used, plz remove import codes `import * as Setting from "../Setting";` to fix the warning

![image](https://user-images.githubusercontent.com/33992371/176343949-8ed5cf01-c8f5-4a2b-8f9a-2211b0670e39.png)

2022-06-29 03:30 UTC, nomeguy approved these changes

2022-06-29 03:31 UTC, merged