feat: prevent csrf attacks with OAuth2.0 state
casdoor/casdoor pull request #892
Opened 2022-07-17 09:36 UTC by RyaoChengfeng

## What's changed

Fix: [#867](https://github.com/casdoor/casdoor/issues/867) [#504](https://github.com/casdoor/casdoor/issues/504) [#564](https://github.com/casdoor/casdoor/issues/564)

1. The frontend gets a random `state` value by requesting `/api/get-oauth-state` and store it in cookies. When send a request to the idp, the state parameter will be added to the request. 
2. After the request is sent, the user is redirected back to the application. The `state` value will be included in this redirect. 
3. Retrieve the returned `state` value and compare it with the one you stored earlier. If the values match, then approve the authentication response and delete `state` in cookies.

2022-07-23 11:06 UTC, hsluoyz commented
@Abingcbc @seriouszyx @Resulte plz review

2022-07-25 13:57 UTC, fanux commented
[sealos](https://github.com/labring/sealos) needs this feature~ : )

2022-07-29 05:48 UTC, RyaoChengfeng commented on web/src/auth/LoginPage.js
> +    this.getOAuthState();
It is only used in oauth, but `href` in the <a></a> tag will call `Provider.getAuthUrl` function when it is rendered, and the state value needs to be obtained before this.

You can see `LoginPage.js` Line 349 and Line 364.

2022-07-29 08:37 UTC, hsluoyz commented
@Abingcbc @seriouszyx plz review again

@fanux can you try this PR to see if it works?

2022-07-29 12:22 UTC, seriouszyx approved these changes
LGTM

2022-07-29 14:22 UTC, Abingcbc commented
LGTM

2022-07-29 15:41 UTC, hsluoyz requested changes

2022-07-29 15:41 UTC, hsluoyz commented on controllers/auth.go
> -				c.ResponseError(fmt.Sprintf("state expected: \"%s\", but got: \"%s\"", conf.GetConfigString("authState"), form.State))
Is `authState` in app.conf not used anywhere after this change? Is yes, plz delete it everywhere

![image](https://user-images.githubusercontent.com/3787410/181794463-ec1092ff-db0c-4531-ba22-9a3ce27a7beb.png)

2022-07-29 15:41 UTC, hsluoyz commented on go.sum
>  github.com/google/uuid v1.1.2/go.mod h1:TIyPZe4MgqvfeYDBFedMoGGpEw/LqOeaOT+nhxU+yHo=
Did you run `go mod tidy`?

2022-07-29 15:41 UTC, hsluoyz commented on go.mod
> +	github.com/google/uuid v1.3.0
Why update the version?

2022-07-29 15:41 UTC, hsluoyz commented on controllers/auth.go
> +		"state": state,
Why not use `ResponseOK()`?

2022-07-29 15:41 UTC, hsluoyz commented on util/random.go
> +func GenerateUuid() string {
Why don't re-use `GenerateClientId` or `GenerateClientSecret`?

2022-07-29 15:41 UTC, hsluoyz commented on web/src/auth/LoginPage.js
> +    this.getOAuthState();
@Abingcbc

2022-07-29 15:50 UTC, RyaoChengfeng commented on go.sum
>  github.com/google/uuid v1.1.2/go.mod h1:TIyPZe4MgqvfeYDBFedMoGGpEw/LqOeaOT+nhxU+yHo=
Yes

2022-07-29 15:53 UTC, hsluoyz commented on go.sum
>  github.com/google/uuid v1.1.2/go.mod h1:TIyPZe4MgqvfeYDBFedMoGGpEw/LqOeaOT+nhxU+yHo=
OK

2022-09-09 09:08 UTC, hsluoyz commented
Already completed

2022-09-09 09:08 UTC, closed without merging